
logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000000

spring:
  rabbitmq:
    host: "localhost"
    port: 5672

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: bajo_stock